Repository CivicActions/accessibility, pull requests merged in 2021-02, with the labels that each got.

#84 Adding initial intro page copy for the Handbook.
  _handbook/introduction.md
Labels: content

#90 Fixing empty link error in accessibility site and adding gitignore
  .gitignore
  _data/header.yml
Labels: website

#94 Pa11y automated testing
  .github/workflows/README.md
  .github/workflows/pa11y.yml
  .gitignore
  .pa11yci
  .pa11yci_with_axe
  VPAT/Drupal9AccessibilityConformanceReport-December2020.html
  _layouts/handbook.html
  _layouts/page.html
  _layouts/people.html
  _layouts/project.html
  package-lock.json
  package.json
  pages/handbook.html
  pages/projects.html
Labels: website

#96 Created the agile.md page and added some of our starting points
  _handbook/resources.md
  pages/about.md
  pages/agile.md
  pages/join.md
Labels: website

#104 Retext feature
  .github/workflows/reviewdog.yml
  VPAT/Readme.md
  lint/Dockerfile
  lint/action.yml
  lint/config/package.json
  lint/config/remarkrc.problem
  lint/config/remarkrc.suggestion
  lint/config/retext.problem.js
  lint/config/retext.suggestion.js
  lint/config/yarn.lock
  lint/remark.sh
  pages/agile.md
Labels: accessibility, website

#109 Added cypress axe and adjusted JavaScript checkers
  _guide/tools.md
  lint/config/remarkrc.problem
Labels: content

#110 Fix empty links guide playbook
  .pa11yci
  _includes/guide.html
  _includes/playbook.html
Labels: accessibility, bug, website

#113 Added CA approach
  _playbook/automated-testing.md
Labels: content

#120 Switching pa11y-ci to run on PR and capture output as comment
  .github/workflows/README.md
  .github/workflows/pa11y.yml
  _config.yml
  package.json
Labels: accessibility, website

#119 Adding an agile statement for this project.
  pages/agile.md
Labels: content
